development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: servsample_development
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: servsample_test
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
